
const bookingData = [
    {
        location: 'Grand Palace',
        slug: 'grand-palace',
        eventType: 'Weddings',
        date: '2025-07-20T18:00',
        guests: 120,
        customer: { name: 'Alice Smith', email: 'alice@example.com' },
        status: 'Confirmed',
        createdAt: '2025-07-10T14:30',
    },
    {
        location: 'Mountain Retreat',
        slug: 'mountain-retreat',
        eventType: 'Meetings',
        date: '2025-07-22T09:30',
        guests: 12,
        customer: { name: 'Bob Johnson', email: 'bob@example.com' },
        status: 'Pending',
        createdAt: '2025-07-11T10:15',
    },
    {
        location: 'City Center Hall',
        slug: 'city-center-hall',
        eventType: 'Conferences',
        date: '2025-08-05T10:00',
        guests: 200,
        customer: { name: 'Charlie Brown', email: 'charlie@example.com' },
        status: 'Cancelled',
        createdAt: '2025-07-12T11:00',
    },
    {
        location: 'Beach Resort',
        slug: 'beach-resort',
        eventType: 'Parties',
        date: '2025-08-15T19:00',
        guests: 50,
        customer: { name: 'Diana Prince', email: 'diana@example.com' },
        status: 'Pending',
        createdAt: '2025-07-13T12:00',
    },
    {
        location: 'Riverside Pavilion',
        slug: 'riverside-pavilion',
        eventType: 'Receptions',
        date: '2025-09-01T15:00',
        guests: 80,
        customer: { name: 'Ethan Hunt', email: 'ethan@example.com' },
        status: 'Confirmed',
        createdAt: '2025-07-14T13:45',
    },
    {
        location: 'Downtown Gallery',
        slug: 'downtown-gallery',
        eventType: 'Exhibitions',
        date: '2025-09-10T11:00',
        guests: 30,
        customer: { name: 'Fiona Gallagher', email: 'fiona@example.com' },
        status: 'Pending',
        createdAt: '2025-07-15T14:00',
    },
    {
        location: 'Skyline Rooftop',
        slug: 'skyline-rooftop',
        eventType: 'Corporate Events',
        date: '2025-09-20T17:00',
        guests: 100,
        customer: { name: 'George Costanza', email: 'george@example.com' },
        status: 'Confirmed',
        createdAt: '2025-07-16T15:30',
    },
    {
        location: 'Garden Terrace',
        slug: 'garden-terrace',
        eventType: 'Family Gatherings',
        date: '2025-10-05T12:00',
        guests: 60,
        customer: { name: 'Hannah Baker', email: 'hannah@example.com' },
        status: 'Pending',
        createdAt: '2025-07-17T16:00',
    },
    {
        location: 'Lakeside Pavilion',
        slug: 'lakeside-pavilion',
        eventType: 'Outdoor Events',
        date: '2025-10-15T14:00',
        guests: 90,
        customer: { name: 'Ian Malcolm', email: 'ian@example.com' },
        status: 'Pending',
        createdAt: '2025-07-18T17:00',
    },
    {
        location: 'Historic Castle',
        slug: 'historic-castle',
        eventType: 'Themed Parties',
        date: '2025-11-01T20:00',
        guests: 150,
        customer: { name: 'Jane Doe', email: 'jane@example.com' },
        status: 'Confirmed',
        createdAt: '2025-07-19T18:00',
    },
    {
        location: 'Art Museum',
        slug: 'art-museum',
        eventType: 'Cultural Events',
        date: '2025-11-10T16:00',
        guests: 40,
        customer: { name: 'Kevin Hart', email: 'kevin@example.com' },
        status: 'Pending',
        createdAt: '2025-07-20T19:00',
    },
];

export {bookingData} 